name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'index.html'  # Only trigger if index.html changes

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload index.html
        uses: actions/upload-pages-artifact@v2
        with:
          path: .  # Current directory

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2

